[default]
SITE_TITLE = "Mini AIP"

# SQLAlchemy
SQLALCHEMY_TRACK_MODIFICATIONS = false
# SQLALCHEMY_DATABASE_URI = "@format {this.DB.URI}"
# SQLALCHEMY_ENGINE_OPTIONS = { max_overflow = 3, pool_size = 2 }
# SQLALCHEMY_ECHO = true

# Sessions
SESSION_TYPE = "filesystem"

# Security
SECURITY_URL_PREFIX = "/auth"
SECURITY_REGISTERABLE = true
SECURITY_RECOVERABLE = true
SECURITY_PASSWORD_COMPLEXITY_CHECKER = "zxcvbn"
SECURITY_PASSWORD_CHECK_BREACHED = "strict"

SECURITY_EMAIL_SENDER = "toto@example.com"
# SECURITY_USER_IDENTITY_ATTRIBUTES = "TODO"

SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = true

DEBUG_TB_ENABLED = false

UNSECURE = true

# RQ
RQ_ASYNC = true
RQ_QUEUES = ["default", "low"]
REDIS_URL = "redis://localhost:6379/0"
RQ_DASHBOARD_REDIS_URL = "@format {this.REDIS_URL}"

# Email
MAIL_USERNAME = "test@example.com"
MAIL_PORT = 587
MAIL_SERVER = "mail.gandi.net"
MAIL_USE_TLS = true
MAIL_USE_SSL = false


[default.CONTENT_SECURITY_POLICY]
default-src = "'none'"
img-src = [ "*", "data:" ]
font-src = [
  "'self'",
  "data:",
  # TODO: remove
  "https://cdnjs.cloudflare.com/",
  "https://fonts.gstatic.com/",
  "https://use.fontawesome.com/",
]
style-src = [
  "'self'",
  "'unsafe-inline'",
  # TODO: remove
  "https://cdnjs.cloudflare.com/",
  "https://fonts.googleapis.com/",
  "https://stackpath.bootstrapcdn.com/",
  "https://use.fontawesome.com/",
]
connect-src = [ "'self'", "https://sentry.io/" ]
object-src = "'none'"
script-src = [
  "'self'",
  "https://sentry.io/",
  "https://www.googletagmanager.com/",
  "https://www.google-analytics.com/",
  "https://www.google.com/",
  "https://www.gstatic.com/",
  "'unsafe-inline'",
  "'unsafe-eval'",
  # TODO: remove
  "https://cdn.jsdelivr.net/",
  "https://cdnjs.cloudflare.com/",
  "https://code.jquery.com/",
  "https://maxcdn.bootstrapcdn.com/",
  "https://stackpath.bootstrapcdn.com/",
]
worker-src = [ "'self'", "blob:" ]
frame-src = [ "'self'", "blob:", "https://www.google.com/" ]
base-uri = "'none'"
form-action = "'self'"


[development]
SERVER_NAME = "127.0.0.1:5000"
PREFERRED_URL_SCHEME = "http"

DB.HOST = "localhost"
DB.DATABASE = "mini_aip"
DB.USER = ""
DB.PASSWORD = ""
DB.URI = "@format postgresql://{this.DB.USER}:{this.DB.PASSWORD}@{this.DB.HOST}/{this.DB.DATABASE}"

SECRET_KEY = "XXX"

DEBUG_TB_INTERCEPT_REDIRECTS = false
#DEBUG_TB_ENABLED = false


[production]
SERVER_NAME = "aip-mini.c17.abilian.com"
PREFERRED_URL_SCHEME = "https"
